// src/routes/(app)/(protected)/favorites/+page.svelte
<script lang="ts">
	import Seo from '$lib/components/seo.svelte';
	import { api } from '$convex/_generated/api';
	import { useQuery } from 'convex-svelte';

	import MaxWidthWrapper from '$lib/components/max-width-wrapper.svelte';
	import PortfolioCard from '$lib/components/portfolio/portfolio-card.svelte';
	import { useSession } from '$lib/hooks/session.svelte.js';

	const session = useSession();

	const getAllFavorites = useQuery(api.favorites.getFavoritesForUser, () =>
		session.isConvexAuthed ? {} : 'skip'
	);
</script>

<Seo title="Favorites" />

<MaxWidthWrapper class="pt-4 md:pt-0">
	<span class="text-3xl font-bold md:hidden md:text-4xl">Favorites</span>

	{#if getAllFavorites.data && getAllFavorites.data.length === 0}
		<div
			class="mt-6 flex h-56 flex-col items-center justify-center gap-4 rounded-md border px-4 text-center"
		>
			<h1 class="text-xl font-bold md:text-2xl">You have no favorites yet!</h1>
			<p class="text-sm text-balance text-muted-foreground md:text-base">
				Start by adding some favorites to your dashboard!
			</p>
		</div>
	{:else}
		<div class="mt-6 grid grid-cols-1 gap-4 pb-10 md:grid-cols-2 lg:grid-cols-3 lg:gap-6">
			{#each getAllFavorites.data ?? [] as item (item._id)}
				<PortfolioCard item={item.portfolioId} isFavoriteCard={true} favoriteId={item._id} />
			{/each}
		</div>
	{/if}
</MaxWidthWrapper>

// src/app/(authenticated)/(main)/favorites/page.tsx
'use client';

import React from 'react';

import MaxWidthWrapper from '@/components/max-width-wrapper';
import PortfolioCard from '@/components/portfolio-card';
import { api } from '@/convex/_generated/api';
import { useQuery } from 'convex/react';

export default function FavoritesPage() {
  const getAllFavorites = useQuery(api.favorites.getFavoritesForUser);

  return (
    <MaxWidthWrapper className="pt-4 md:pt-0">
      <span className="text-3xl md:text-4xl font-bold md:hidden">
        Favorites
      </span>

      {getAllFavorites && getAllFavorites.length === 0 ? (
        <div className="flex flex-col items-center gap-4 mt-6 border rounded-md h-56 justify-center text-center px-4">
          <h1 className="text-xl md:text-2xl font-bold">
            You have no favorites yet!
          </h1>
          <p className="text-sm md:text-base text-muted-foreground text-balance">
            Start by adding some favorites to your dashboard!
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 lg:gap-6 mt-6 pb-10">
          {getAllFavorites?.map((item) => {
            return (
              <PortfolioCard
                key={item._id}
                item={item.portfolioId}
                isFavoriteCard={true}
                favoriteId={item._id}
              />
            );
          })}
        </div>
      )}
    </MaxWidthWrapper>
  );
}
