// src/app/(main)/changelog/page.tsx
import { unstable_noStore } from 'next/cache';

import { format } from 'date-fns';
import Markdown from 'react-markdown';

type ChangeLog = {
  id: string;
  date: string;
  title: string;
  post: string;
};

export default async function ChangelogPage() {
  unstable_noStore();

  const changelogs = await fetch(
    `https://projectplannerai.com/api/changelog?projectId=j573djhyyk1jvsf7mxxfgqh1z96pm5hc`,
  ).then(async (res) => res.json() as Promise<ChangeLog[]>);

  return (
    <div className="w-full container mx-auto">
      <div className="flex flex-row justify-between mb-8">
        <h1 className="my-12 text-[28px] leading-[34px] tracking-[-0.416px] text-neutral-12 font-bold">
          Changelog
        </h1>
      </div>

      {changelogs.length === 0 && (
        <div className="text-lg font-semibold">No changelogs found</div>
      )}

      <ul className="flex flex-col">
        {changelogs.map((changelog) => (
          <li
            key={changelog.id}
            className="relative flex w-full flex-col sm:flex-row"
          >
            <div className="flex w-full pb-4 sm:w-[200px] sm:pb-0">
              <p className="sans text-sm leading-[1.6] text-slate-11 font-normal">
                <time className="sticky top-24 text-xl" dateTime="2024-03-06">
                  {format(changelog.date, 'PP')}
                </time>
              </p>
            </div>

            <div className="relative hidden sm:flex sm:w-[100px]">
              <div className="absolute left-0.5 top-0.5 h-full w-0.5 bg-slate-200"></div>
              <div className="sticky left-0 top-[102px] mt-1.5 h-1.5 w-1.5 rounded-full bg-white"></div>
            </div>

            <div className="w-full pb-16">
              <div className="space-y-4">
                <div className="flex flex-col gap-4">
                  <h2 className="text-4xl">{changelog.title}</h2>

                  <Markdown className="prose text-white">
                    {changelog.post}
                  </Markdown>
                </div>
              </div>
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}

// src/routes/(app)/changelog/+page.svelte
<script lang="ts">
	import { format } from 'date-fns';

	import Seo from '$lib/components/seo.svelte';

	let { data } = $props();
</script>

<Seo title="Changelog" />

<div class="container mx-auto w-full">
	<div class="mb-8 flex flex-row justify-between">
		<h1 class="text-neutral-12 my-12 text-[28px] leading-[34px] font-bold tracking-[-0.416px]">
			Changelog
		</h1>
	</div>

	{#if data.changelogs.length === 0}
		<div class="text-lg font-semibold">No changelogs found</div>
	{/if}

	<ul class="flex flex-col">
		{#each data.changelogs as changelog (changelog.id)}
			<li class="relative flex w-full flex-col sm:flex-row">
				<div class="flex w-full pb-4 sm:w-[200px] sm:pb-0">
					<p class="sans text-slate-11 text-sm leading-[1.6] font-normal">
						<time class="sticky top-24 text-xl" datetime={changelog.date}>
							{format(changelog.date, 'PP')}
						</time>
					</p>
				</div>

				<div class="relative hidden sm:flex sm:w-[100px]">
					<div class="absolute top-0.5 left-0.5 h-full w-0.5 bg-slate-200"></div>
					<div class="sticky top-[102px] left-0 mt-1.5 h-1.5 w-1.5 rounded-full bg-white"></div>
				</div>

				<div class="w-full pb-16">
					<div class="space-y-4">
						<div class="flex flex-col gap-4">
							<h2 class="text-4xl">{changelog.title}</h2>
							<div class="prose text-white">{@html changelog.html}</div>
						</div>
					</div>
				</div>
			</li>
		{/each}
	</ul>
</div>
