// src/app/(main)/admin/page.tsx
'use client';

import React, { useState } from 'react';

import Image from 'next/image';
import Link from 'next/link';

import MaxWidthWrapper from '@/components/max-width-wrapper';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { api } from '@/convex/_generated/api';
import { getImageUrl } from '@/lib/get-image-url';
import { cn } from '@/lib/utils';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery } from 'convex/react';
import { Image as ImageIcon, Loader2 } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { toast } from 'sonner';
import { z } from 'zod';

const editFormSchema = z.object({
  name: z.string().min(2).max(50),
  link: z.string().url(),
  tags: z.string(),
  image: z.string(),
});

const deleteFormSchema = z.object({
  submissionId: z.string(),
});

function EditForm({ setOpen, item }: { setOpen: any; item: any }) {
  const [image, setImage] = useState<any>(null);
  const [imageUrl, setImageUrl] = useState<string | null>(
    item?.image ? getImageUrl(item?.image) : null,
  );
  // Ensure default values are never undefined
  const form = useForm<z.infer<typeof editFormSchema>>({
    resolver: zodResolver(editFormSchema),
    defaultValues: {
      name: item?.name || '',
      link: item?.link || '',
      tags: item?.tags || [],
      image: item?.image || '',
    },
  });

  const isSubmitting = form.formState.isSubmitting;

  const generateUploadUrl = useMutation(api.uploads.generateUploadUrl);

  const createPortfolio = useMutation(api.portfolios.createPortfolio);
  const updateSubmission = useMutation(api.submissions.updateSubmission);

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0] || null;
    if (file) {
      setImage(file);
      const url = URL.createObjectURL(file);
      setImageUrl(url);
    } else {
      setImageUrl(null);
    }
  };

  async function onSubmit(values: z.infer<typeof editFormSchema>) {
    const formattedTages = values.tags.split(',').map((item) => item.trim());

    // Update the submission if it exists
    await updateSubmission({
      submissionId: item?._id,
      name: values.name,
      link: values.link,
      status: 'completed',
    });

    // Get Image storage id
    const postUrl = await generateUploadUrl();
    const result = await fetch(postUrl, {
      method: 'POST',
      headers: { 'Content-Type': image!.type },
      body: image,
    });
    const { storageId } = await result.json();
    // Add the new submission to portfolios
    await createPortfolio({
      name: values.name,
      link: values.link,
      tags: formattedTages,
      image: storageId,
    });

    // Close the dialog
    setOpen(false);

    // Show success message
    toast.success('Submitted successfully!');
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
        <label htmlFor="file-upload" className="cursor-pointer">
          <div className="h-36  rounded-md border border-dashed items-center justify-center flex flex-col gap-2">
            {imageUrl ? (
              <Image
                src={imageUrl}
                alt="Uploaded"
                width={400}
                height={200}
                priority
                className="object-cover overflow-hidden object-top w-full rounded-md"
              />
            ) : (
              <>
                <ImageIcon className="stroke-muted-foreground" />
                <span className="text-xs text-muted-foreground">
                  Upload image
                </span>
              </>
            )}
            <input
              id="file-upload"
              type="file"
              accept="image/*"
              onChange={handleFileChange}
              className="hidden"
            />
          </div>
        </label>
        <FormField
          control={form.control}
          name="name"
          render={({ field }) => (
            <FormItem className="flex flex-row gap-2 items-center">
              <FormLabel className="w-20">Name</FormLabel>
              <FormControl>
                <Input placeholder="Hosna Qasmei" {...field} />
              </FormControl>
            </FormItem>
          )}
        />

        <FormField
          control={form.control}
          name="link"
          render={({ field }) => (
            <FormItem className="flex flex-row gap-2 items-center">
              <FormLabel className="w-20">Website</FormLabel>
              <FormControl>
                <Input placeholder="https://www.example.com" {...field} />
              </FormControl>
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="tags"
          render={({ field }) => (
            <FormItem className="flex flex-row gap-2 items-center">
              <FormLabel className="w-20">Tags</FormLabel>
              <FormControl>
                <Input placeholder="Developer, Designer" {...field} />
              </FormControl>
            </FormItem>
          )}
        />
        <div className="justify-end w-full flex">
          <Button type="submit" disabled={isSubmitting}>
            {isSubmitting ? (
              <div className="flex gap-2 items-center">
                <Loader2 className="animate-spin h-4 w-4" />
                <span>Submit</span>
              </div>
            ) : (
              <span>Submit</span>
            )}
          </Button>
        </div>
      </form>
    </Form>
  );
}

function DeleteForm({
  setOpen,
  submissionId,
}: {
  setOpen: any;
  submissionId: any;
}) {
  const form = useForm<z.infer<typeof deleteFormSchema>>({
    resolver: zodResolver(deleteFormSchema),
    defaultValues: { submissionId: submissionId },
  });
  const isLoading = form.formState.isSubmitting;
  const deleleSubmission = useMutation(api.submissions.deleteSubmission);

  const onSubmit = async () => {
    try {
      await deleleSubmission({ submissionId });
      setOpen(false);
      toast.success('Deleted successfully!');
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)}>
        <div className="w-full flex justify-center space-x-6">
          <Button
            size="lg"
            variant="outline"
            disabled={isLoading}
            className="w-full"
            type="button"
            onClick={() => setOpen(false)}
          >
            Cancel
          </Button>
          <Button
            size="lg"
            type="submit"
            disabled={isLoading}
            className="w-full bg-red-500 hover:bg-red-400"
          >
            {isLoading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Deleting
              </>
            ) : (
              <span>Delete</span>
            )}
          </Button>
        </div>
      </form>
    </Form>
  );
}
export default function Admin() {
  const [item, setItem] = useState<any>(null);
  const submissions = useQuery(api.submissions.getSubmissions);
  const [isEditOpen, setIsEditOpen] = useState(false);
  const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const user = useQuery(api.users.getMyUser);

  if (user?.isAdmin !== true) {
    return (
      <div className="text-muted-foreground py-16 flex flex-col items-center justify-center">
        <span>Sorry, you can not access this page.</span>
        <span>You need to be an admin.</span>
      </div>
    );
  }

  return (
    <>
      <MaxWidthWrapper>
        <span className="text-4xl font-bold">Submissions</span>
        {submissions?.length === 0 ? (
          <div className="flex mt-4 items-center justify-center py-16 border rounded-md">
            <span className="text-muted-foreground">
              No submissions to review
            </span>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-4">
            {submissions?.map((submission, idx) => (
              <Card
                key={idx}
                className="w-full rounded-md border border-border shadow-sm p-6"
              >
                <div className="relative flex flex-col gap-2">
                  <Link
                    href={submission.link}
                    target="_blank"
                    className="flex flex-col gap-2"
                  >
                    <div>
                      <Badge
                        className={cn(
                          'capitalize text-foreground',
                          submission.status === 'pending' &&
                            'bg-yellow-700 hover:bg-yellow-800',
                          submission.status === 'completed' &&
                            'bg-green-700 hover:bg-green-800',
                        )}
                      >
                        {submission.status}
                      </Badge>
                    </div>
                    <span className="text-xl font-bold">{submission.name}</span>
                  </Link>

                  <div className="flex gap-2 items-center justify-start">
                    {submission.status === 'pending' ? (
                      <Button
                        size="sm"
                        onClick={() => {
                          setItem(submission);
                          setIsEditOpen(true);
                        }}
                      >
                        Submit
                      </Button>
                    ) : (
                      <Button
                        size="sm"
                        variant="destructive"
                        onClick={() => {
                          setItem(submission);
                          setIsDeleteOpen(true);
                        }}
                      >
                        Delete
                      </Button>
                    )}
                  </div>
                </div>
              </Card>
            ))}
          </div>
        )}
      </MaxWidthWrapper>

      <Dialog open={isEditOpen} onOpenChange={setIsEditOpen}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>Edit submission</DialogTitle>
          </DialogHeader>
          <EditForm setOpen={setIsEditOpen} item={item} />
        </DialogContent>
      </Dialog>

      <Dialog open={isDeleteOpen} onOpenChange={setIsDeleteOpen}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>Delete submission</DialogTitle>
          </DialogHeader>
          <DeleteForm setOpen={setIsDeleteOpen} submissionId={item?._id} />
        </DialogContent>
      </Dialog>
    </>
  );
}

// src/routes/(app)/(protected)/admin/+page.svelte
<script lang="ts">
	import Seo from '$lib/components/seo.svelte';
	import { api } from '$convex/_generated/api';
	import { useMutation, useQuery } from 'convex-svelte';

	import DeleteConfirmForm from '$lib/components/admin/delete-confirm-form.svelte';
	import PortfolioForm from '$lib/components/admin/portfolio-form.svelte';
	import MaxWidthWrapper from '$lib/components/max-width-wrapper.svelte';
	import { Badge } from '$lib/components/ui/badge/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Card from '$lib/components/ui/card/index.js';
	import * as Dialog from '$lib/components/ui/dialog/index.js';
	import { useSession } from '$lib/hooks/session.svelte.js';
	import { cn } from '$lib/utils.js';

	const session = useSession();

	// Gated on the Convex token so the denial block doesn't flash for admins.
	const gate = $derived(session.isConvexAuthed ? {} : ('skip' as const));

	const user = useQuery(api.users.getMyUser, () => gate);
	const submissions = useQuery(api.submissions.getSubmissions, () => gate);
	const portfolios = useQuery(api.portfolios.getAllPortfolios, {});

	const deletePortfolio = useMutation(api.portfolios.delelePortfolio);
	const deleteSubmission = useMutation(api.submissions.deleteSubmission);

	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	let item = $state<any>(null);
	let isAddPortfolio = $state(false);
	let isEditOpen = $state(false);
	let isDeleteSubmissionOpen = $state(false);
	let isDeletePortfolioOpen = $state(false);
</script>

<Seo title="Admin" />

{#if user.data?.isAdmin !== true}
	<div class="flex flex-col items-center justify-center py-16 text-muted-foreground">
		<span>Sorry, you can not access this page.</span>
		<span>You need to be an admin.</span>
	</div>
{:else}
	<MaxWidthWrapper class="gap-4 pt-4">
		<div>
			<span class="text-3xl font-bold md:text-4xl">Submissions</span>
			{#if submissions.data?.length === 0}
				<div class="mt-4 flex items-center justify-center rounded-md border py-16">
					<span class="text-muted-foreground">No submissions to review</span>
				</div>
			{:else}
				<div class="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
					{#each submissions.data ?? [] as submission (submission._id)}
						<Card.Root class="w-full rounded-md border border-border p-6 shadow-xs">
							<div class="relative flex flex-col gap-2">
								<a
									href={submission.link}
									target="_blank"
									rel="noopener noreferrer"
									class="flex flex-col gap-2"
								>
									<div>
										<Badge
											class={cn(
												'text-foreground capitalize',
												submission.status === 'pending' && 'bg-yellow-700 hover:bg-yellow-800',
												submission.status === 'completed' && 'bg-green-700 hover:bg-green-800'
											)}
										>
											{submission.status}
										</Badge>
									</div>
									<span class="text-xl font-bold">{submission.name}</span>
								</a>

								<div class="flex items-center justify-start gap-2">
									{#if submission.status === 'pending'}
										<Button
											size="sm"
											onclick={() => {
												item = submission;
												isAddPortfolio = true;
											}}
										>
											Submit
										</Button>
									{:else}
										<Button
											size="sm"
											variant="destructive"
											onclick={() => {
												item = submission;
												isDeleteSubmissionOpen = true;
											}}
										>
											Delete
										</Button>
									{/if}
								</div>
							</div>
						</Card.Root>
					{/each}
				</div>
			{/if}
		</div>
		<div>
			<span class="text-3xl font-bold md:text-4xl">Portfolios</span>
			{#if portfolios.data?.length === 0}
				<div class="mt-4 flex items-center justify-center rounded-md border py-16">
					<span class="text-muted-foreground">No portfolios</span>
				</div>
			{:else}
				<div class="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
					{#each portfolios.data ?? [] as portfolio (portfolio._id)}
						<Card.Root class="w-full rounded-md border border-border p-6 shadow-xs">
							<div class="relative flex flex-col gap-2">
								<a
									href={portfolio.link}
									target="_blank"
									rel="noopener noreferrer"
									class="flex flex-col gap-2"
								>
									<div>
										{#if !portfolio.socials}
											<Badge class="bg-orange-500 text-white">Need to update socials</Badge>
										{/if}
									</div>
									<span class="text-xl font-bold">{portfolio.name}</span>
								</a>

								<div class="flex items-center justify-start gap-2">
									<Button
										size="sm"
										onclick={() => {
											item = portfolio;
											isEditOpen = true;
										}}
									>
										Update
									</Button>
									<Button
										size="sm"
										variant="destructive"
										onclick={() => {
											item = portfolio;
											isDeletePortfolioOpen = true;
										}}
									>
										Delete
									</Button>
								</div>
							</div>
						</Card.Root>
					{/each}
				</div>
			{/if}
		</div>
	</MaxWidthWrapper>

	<!-- Add Portfolio Form -->
	<Dialog.Root bind:open={isAddPortfolio}>
		<Dialog.Content class="sm:max-w-[425px]">
			<Dialog.Header>
				<Dialog.Title>Add portfolio</Dialog.Title>
			</Dialog.Header>
			{#key item?._id}
				<PortfolioForm bind:open={isAddPortfolio} mode="add" {item} />
			{/key}
		</Dialog.Content>
	</Dialog.Root>

	<!-- Delete Submission Form -->
	<Dialog.Root bind:open={isDeleteSubmissionOpen}>
		<Dialog.Content class="sm:max-w-[425px]">
			<Dialog.Header>
				<Dialog.Title>Delete submission</Dialog.Title>
			</Dialog.Header>
			<DeleteConfirmForm
				bind:open={isDeleteSubmissionOpen}
				onConfirm={() => deleteSubmission({ submissionId: item._id })}
			/>
		</Dialog.Content>
	</Dialog.Root>

	<!-- Delete Portfolio Form -->
	<Dialog.Root bind:open={isDeletePortfolioOpen}>
		<Dialog.Content class="sm:max-w-[425px]">
			<Dialog.Header>
				<Dialog.Title>Delete portfolio</Dialog.Title>
			</Dialog.Header>
			<DeleteConfirmForm
				bind:open={isDeletePortfolioOpen}
				onConfirm={() => deletePortfolio({ portfolioId: item._id, portfolioImageId: item.image })}
			/>
		</Dialog.Content>
	</Dialog.Root>

	<!-- Edit Portfolio Form -->
	<Dialog.Root bind:open={isEditOpen}>
		<Dialog.Content class="sm:max-w-[425px]">
			<Dialog.Header>
				<Dialog.Title>Edit portfolio</Dialog.Title>
			</Dialog.Header>
			{#key item?._id}
				<PortfolioForm bind:open={isEditOpen} mode="edit" {item} />
			{/key}
		</Dialog.Content>
	</Dialog.Root>
{/if}
