// src/lib/components/portfolio/content.svelte
<script lang="ts">
	import FilterAndSortBar from './filter-and-sort-bar.svelte';
	import MainContent from './main-content.svelte';

	// The Next app duplicated this state in (landing)/_components/content.tsx and
	// dashboard/page.tsx; both now use this one component.
	let selectedSort = $state('recentlyAdded');
	let selectedFilter = $state('All');
	let searchValue = $state('');
</script>

<div class="py-6">
	<FilterAndSortBar bind:searchValue bind:selectedSort bind:selectedFilter />
	<MainContent {selectedSort} {selectedFilter} {searchValue} />
</div>

// src/app/(unauthenticated)/(landing)/_components/content.tsx
'use client';

import React, { useState } from 'react';

import FilterAndSortBar from '@/components/filter-and-sort-bar';
import MainContent from '@/components/main-content';

export default function Content() {
  const [selectedSort, setSelectedSort] = useState<string>('recentlyAdded');
  const [selectedFilter, setSelectedFilter] = useState<string>('All');
  const [searchValue, setSearchValue] = useState('');

  return (
    <div className="py-6 ">
      <FilterAndSortBar
        searchValue={searchValue}
        selectedSort={selectedSort}
        selectedFilter={selectedFilter}
        setSearchValue={setSearchValue}
        setSelectedSort={setSelectedSort}
        setSelectedFilter={setSelectedFilter}
      />
      <MainContent
        selectedSort={selectedSort}
        selectedFilter={selectedFilter}
        searchValue={searchValue}
      />
    </div>
  );
}
