// src/lib/components/scroll-to-top-button.svelte
<script lang="ts">
	import ChevronUpIcon from '@lucide/svelte/icons/chevron-up';

	// Replaces the Next app's useState/useEffect scroll listener.
	let scrollY = $state(0);
	const isVisible = $derived(scrollY > 300);

	function scrollToTop() {
		window.scrollTo({ top: 0, behavior: 'smooth' });
	}
</script>

<svelte:window bind:scrollY />

{#if isVisible}
	<button
		onclick={scrollToTop}
		aria-label="Scroll to top"
		class="fixed right-4 bottom-4 z-50 flex h-10 w-10 items-center justify-center rounded-full bg-foreground font-medium text-background shadow transition duration-300 ease-in-out md:right-12 md:bottom-12"
	>
		<ChevronUpIcon class="mb-0.5 stroke-[2.25px]" size={24} />
	</button>
{/if}

// apps/web/src/components/scroll-to-top-button.tsx
'use client';

import React, { useEffect, useState } from 'react';

import { ArrowUpToLine } from 'lucide-react';

export default function ScrollToTopButton() {
  const [isVisible, setIsVisible] = useState(false);

  // Toggle visibility based on scroll position
  useEffect(() => {
    const toggleVisibility = () => {
      if (window.pageYOffset > 300) {
        setIsVisible(true);
      } else {
        setIsVisible(false);
      }
    };

    window.addEventListener('scroll', toggleVisibility);
    return () => window.removeEventListener('scroll', toggleVisibility);
  }, []);

  // Scroll to top function
  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: 'smooth',
    });
  };

  if (!isVisible) return null;

  return (
    <button
      onClick={scrollToTop}
      className="fixed bottom-6 right-6 md:bottom-12 md:right-12 z-50 bg-foreground text-background font-medium h-10 w-10  items-center justify-center flex rounded-full shadow transition ease-in-out duration-300"
    >
      <ArrowUpToLine size={20} />
    </button>
  );
}
