// src/app/(unauthenticated)/blog/page.tsx
'use client';

import React from 'react';

import MaxWidthWrapper from '@/components/max-width-wrapper';

export default function BlogPage() {
  return (
    <MaxWidthWrapper>
      <span className="text-2xl md:text-4xl font-bold">Blog</span>
      <div className="pb-6 pt-2 relative"></div>
    </MaxWidthWrapper>
  );
}

// src/routes/(app)/blog/+page.svelte
<script lang="ts">
	import Seo from '$lib/components/seo.svelte';
	import MaxWidthWrapper from '$lib/components/max-width-wrapper.svelte';
</script>

<Seo title="Blog" />

<MaxWidthWrapper>
	<span class="text-2xl font-bold md:text-4xl">Blog</span>
	<div class="relative pt-2 pb-6"></div>
</MaxWidthWrapper>
