// src/lib/components/forms/feedback-form.svelte
<script lang="ts">
	import { env } from '$env/dynamic/public';
	import Loader2Icon from '@lucide/svelte/icons/loader-2';
	import { toast } from 'svelte-sonner';
	import { defaults, superForm } from 'sveltekit-superforms';
	import { zod } from 'sveltekit-superforms/adapters';

	import { Button } from '$lib/components/ui/button/index.js';
	import * as Form from '$lib/components/ui/form/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { Textarea } from '$lib/components/ui/textarea/index.js';
	import { feedbackFormSchema } from '$lib/schemas/feedback.js';

	let { open = $bindable(true) }: { open?: boolean } = $props();

	// SPA mode: this posts cross-origin to projectplannerai from inside a modal,
	// so there is no SvelteKit form action to progressively enhance. superforms
	// is used because shadcn-svelte's Form.* components require its context.
	const form = superForm(defaults(zod(feedbackFormSchema)), {
		SPA: true,
		validators: zod(feedbackFormSchema),
		onUpdate: async ({ form: f }) => {
			if (!f.valid) return;
			await fetch('https://projectplannerai.com/api/feedback', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({
					projectId: env.PUBLIC_PROJECT_PLANNER_AI_ID,
					feedback: f.data.feedback,
					name: f.data.name,
					email: f.data.email
				})
			});
			open = false;
			toast.success('Feedback successfully submitted! ');
		}
	});

	const { form: formData, enhance, submitting } = form;
</script>

<form method="POST" use:enhance class="space-y-4 px-4 pb-4 md:px-0 md:pb-0">
	<Form.Field {form} name="name">
		<Form.Control>
			{#snippet children({ props })}
				<Form.Label>Your name</Form.Label>
				<!-- svelte-ignore a11y_autofocus -->
				<Input {...props} bind:value={$formData.name} placeholder="Hosna Qasmei" autofocus />
			{/snippet}
		</Form.Control>
		<Form.FieldErrors />
	</Form.Field>

	<Form.Field {form} name="email">
		<Form.Control>
			{#snippet children({ props })}
				<Form.Label>Your email</Form.Label>
				<Input {...props} bind:value={$formData.email} placeholder="test@example.com" />
			{/snippet}
		</Form.Control>
		<Form.FieldErrors />
	</Form.Field>

	<Form.Field {form} name="feedback">
		<Form.Control>
			{#snippet children({ props })}
				<Form.Label>Feedback</Form.Label>
				<Textarea
					{...props}
					bind:value={$formData.feedback}
					placeholder="Can you please add light mode"
				/>
			{/snippet}
		</Form.Control>
		<Form.FieldErrors />
	</Form.Field>

	<div class="flex w-full justify-end">
		<Button type="submit" disabled={$submitting}>
			{#if $submitting}
				<Loader2Icon class="h-4 w-4 animate-spin" />
			{:else}
				<span>Submit</span>
			{/if}
		</Button>
	</div>
</form>

// src/app/(main)/_components/forms/feedback-form.tsx
'use client';

import React from 'react';

import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { zodResolver } from '@hookform/resolvers/zod';
import { Loader2 } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { toast } from 'sonner';
import { z } from 'zod';

const feedbackFormSchema = z.object({
  name: z.string().min(2).max(50),
  email: z.string().email(),
  feedback: z.string().min(2).max(500),
});

export default function FeedbackForm({ setOpen }: { setOpen: any }) {
  const form = useForm<z.infer<typeof feedbackFormSchema>>({
    resolver: zodResolver(feedbackFormSchema),
    defaultValues: {
      name: '',
      email: '',
      feedback: '',
    },
  });

  const isSubmitting = form.formState.isSubmitting;
  async function onSubmit(values: z.infer<typeof feedbackFormSchema>) {
    await fetch('https://projectplannerai.com/api/feedback', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        projectId: process.env.NEXT_PUBLIC_PROJECT_PLANNER_AI_ID,
        feedback: values.feedback,
        name: values.name,
        email: values.email,
      }),
    });
    setOpen(false);
    toast.success('Feedback successfully submitted! ');
  }
  return (
    <Form {...form}>
      <form
        onSubmit={form.handleSubmit(onSubmit)}
        className="space-y-4 px-4 pb-4 md:px-0 md:pb-0"
      >
        <FormField
          control={form.control}
          name="name"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Your name</FormLabel>
              <FormControl>
                <Input placeholder="Hosna Qasmei" {...field} autoFocus />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />

        <FormField
          control={form.control}
          name="email"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Your email</FormLabel>
              <FormControl>
                <Input placeholder="test@example.com" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />

        <FormField
          control={form.control}
          name="feedback"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Feedback</FormLabel>
              <FormControl>
                <Textarea
                  placeholder="Can you please add light mode"
                  {...field}
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />

        <div className="justify-end w-full flex">
          <Button type="submit" disabled={isSubmitting}>
            {isSubmitting ? (
              <Loader2 className="animate-spin h-4 w-4" />
            ) : (
              <span>Submit</span>
            )}
          </Button>
        </div>
      </form>
    </Form>
  );
}
