// src/lib/components/forms/submission-form.svelte
<script lang="ts">
	import { api } from '$convex/_generated/api';
	import Loader2Icon from '@lucide/svelte/icons/loader-2';
	import { useMutation } from 'convex-svelte';
	import { toast } from 'svelte-sonner';
	import { defaults, superForm } from 'sveltekit-superforms';
	import { zod } from 'sveltekit-superforms/adapters';

	import { Button } from '$lib/components/ui/button/index.js';
	import * as Form from '$lib/components/ui/form/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { submissionFormSchema } from '$lib/schemas/submission.js';

	let { open = $bindable(true) }: { open?: boolean } = $props();

	const createSubmission = useMutation(api.submissions.createSubmission);

	const form = superForm(defaults(zod(submissionFormSchema)), {
		SPA: true,
		validators: zod(submissionFormSchema),
		onUpdate: async ({ form: f }) => {
			if (!f.valid) return;
			await createSubmission({ name: f.data.name, link: f.data.link });
			open = false;
			toast.success(
				'Your portfolio has been submitted! We will review it shortly. It should appear within a few hours.'
			);
		}
	});

	const { form: formData, enhance, submitting } = form;
</script>

<form method="POST" use:enhance class="space-y-4 px-4 pb-4 md:px-0 md:pb-0">
	<Form.Field {form} name="name">
		<Form.Control>
			{#snippet children({ props })}
				<Form.Label>Name</Form.Label>
				<!-- svelte-ignore a11y_autofocus -->
				<Input {...props} bind:value={$formData.name} placeholder="Hosna Qasmei" autofocus />
			{/snippet}
		</Form.Control>
		<Form.FieldErrors />
	</Form.Field>

	<Form.Field {form} name="link">
		<Form.Control>
			{#snippet children({ props })}
				<Form.Label>Portfolio website</Form.Label>
				<Input {...props} bind:value={$formData.link} placeholder="https://www.example.com" />
			{/snippet}
		</Form.Control>
		<Form.FieldErrors />
	</Form.Field>

	<div class="flex w-full justify-end">
		<Button type="submit" disabled={$submitting}>
			{#if $submitting}
				<Loader2Icon class="h-4 w-4 animate-spin" />
			{:else}
				<span>Submit</span>
			{/if}
		</Button>
	</div>
</form>

// src/app/(main)/_components/forms/submission-form.tsx
'use client';

import React from 'react';



import { Button } from '@/components/ui/button';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { api } from '@/convex/_generated/api';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation } from 'convex/react';
import { Loader2 } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { toast } from 'sonner';
import { z } from 'zod';





const submissionFormSchema = z.object({
  name: z.string().min(2).max(50),
  link: z.string().url(),
});

export default function SubmissionForm({ setOpen }: { setOpen: any }) {
  const form = useForm<z.infer<typeof submissionFormSchema>>({
    resolver: zodResolver(submissionFormSchema),
    defaultValues: {
      name: '',
      link: '',
    },
  });

  const isSubmitting = form.formState.isSubmitting;

  const createSubmission = useMutation(api.submissions.createSubmission);

  async function onSubmit(values: z.infer<typeof submissionFormSchema>) {
    await createSubmission({
      name: values.name,
      link: values.link,
    });
    setOpen(false);
    toast.success(
      'Your portfolio has been submitted! We will review it shortly. It should appear within a few hours.',
    );
  }

  return (
    <Form {...form}>
      <form
        onSubmit={form.handleSubmit(onSubmit)}
        className="space-y-4 px-4 pb-4 md:px-0 md:pb-0"
      >
        <FormField
          control={form.control}
          name="name"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Name</FormLabel>
              <FormControl>
                <Input placeholder="Hosna Qasmei" {...field} autoFocus/>
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />

        <FormField
          control={form.control}
          name="link"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Portfolio website</FormLabel>
              <FormControl>
                <Input placeholder="https://www.example.com" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <div className="justify-end w-full flex">
          <Button type="submit" disabled={isSubmitting}>
            {isSubmitting ? (
              <Loader2 className="animate-spin h-4 w-4" />
            ) : (
              <span>Submit</span>
            )}
          </Button>
        </div>
      </form>
    </Form>
  );
}
