// src/app/(main)/_components/hero.tsx
'use client';

import React from 'react';

import Counter from '@/components/counter';
import { Spotlight } from '@/components/spotlight';

export default function Hero() {
  return (
    <div className="flex flex-col items-center justify-center text-center pt-16">
      <div className="w-full flex flex-col gap-6 mb-8">
        <Spotlight
          className="-top-40 left-0 md:left-[300px] md:-top-20"
          fill="white"
        />
        <div className="flex flex-col items-center gap-y-6 sm:gap-y-7">
          <h1 className="text-pretty text-neutral-900 dark:text-white lg:text-6xl lg:-tracking-4 lg:leading-[4rem] lg:font-extrabold text-4xl md:text-5xl -tracking-3 font-bold max-w-3xl text-center">
            Discover portfolios to inspire your creativity
          </h1>
        </div>
        <p className="text-neutral-700 dark:text-neutral-300 mx-auto block text-balance max-w-sm text-center text-base md:max-w-3xl md:text-lg xl:text-xl">
          Browse our curated collection of{' '}
          <span className="text-foreground font-semibold">
            <Counter value={217} className="text-foreground font-semibold" />+
          </span>{' '}
          exceptional designs and showcase your own work.
        </p>
      </div>
    </div>
  );
}

// src/lib/components/portfolio/hero.svelte
<script lang="ts">
	import { api } from '$convex/_generated/api';
	import { useQuery } from 'convex-svelte';

	const portfolios = useQuery(api.portfolios.getAllPortfolios, {});
	const numberOfPortfolios = $derived(portfolios.data?.length);
</script>

<div class="flex flex-col items-center gap-y-6 pt-6 sm:pt-14">
	<h1
		class="lg:-tracking-4 -tracking-3 max-w-3xl text-center text-4xl font-bold text-pretty text-neutral-900 md:text-5xl lg:text-6xl lg:leading-[4rem] lg:font-extrabold dark:text-white"
	>
		Best place to find{' '}
		<span class="relative inline-block">
			portfolio
			<svg
				class="absolute -bottom-1 left-0 h-3 w-full"
				viewBox="0 0 200 9"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
			>
				<path
					d="M1 7.5C31 3.5 61 3.5 91 3.5C121 3.5 151 3.5 181 7.5"
					stroke="url(#paint0_linear)"
					stroke-width="2"
					stroke-linecap="round"
				/>
				<defs>
					<linearGradient
						id="paint0_linear"
						x1="1"
						y1="5"
						x2="181"
						y2="5"
						gradientUnits="userSpaceOnUse"
					>
						<stop stop-color="#34d399" />
						<stop offset="1" stop-color="#059669" />
					</linearGradient>
				</defs>
			</svg>
		</span>{' '}
		inspiration
	</h1>
</div>
<p
	class="mx-auto block max-w-sm text-center text-base text-balance text-neutral-700 md:max-w-3xl md:text-lg xl:text-xl dark:text-neutral-300"
>
	Browse our curated collection of{' '}
	{#if numberOfPortfolios}
		<span class="font-semibold text-foreground">{numberOfPortfolios}+</span>
	{/if}{' '}
	exceptional designs to help you create your best portfolio yet.
</p>
