// apps/web/src/components/main-content-skeleton.tsx
import React from 'react';

import { Card, CardContent } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';

export default function MainContentSkeleton() {
  return (
    <div className="flex flex-col gap-4">
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 lg:gap-6">
        {Array.from({ length: 6 }).map((_, idx) => (
          <Card
            key={idx}
            className="w-full rounded-md border border-border shadow-sm relative"
          >
            <div className="px-3 pt-3">
              <div className="overflow-hidden rounded-md ">
                <Skeleton className="h-56 object-top" />
              </div>
            </div>

            <CardContent className="px-3 py-3">
              <Skeleton className="h-6 w-36" />
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

// src/lib/components/portfolio/main-content-skeleton.svelte
<script lang="ts">
	import * as Card from '$lib/components/ui/card/index.js';
	import { Skeleton } from '$lib/components/ui/skeleton/index.js';
</script>

<div class="flex flex-col gap-4">
	<div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3 lg:gap-6">
		{#each Array.from({ length: 6 }) as _, idx (idx)}
			<Card.Root class="relative w-full">
				<div>
					<div class="overflow-hidden rounded-t-lg border-b">
						<Skeleton class="h-80 rounded-none object-top" />
					</div>
				</div>

				<Card.Content class="flex px-4 py-3">
					<Skeleton class="h-6 w-36" />
				</Card.Content>
			</Card.Root>
		{/each}
	</div>
</div>
