// src/routes/(app)/privacy-policy/+page.svelte
<script lang="ts">
	// mdsvex compiles the .svx at build time, so this replaces both
	// src/lib/posts.ts (which read the filesystem) and next-mdx-remote.
	import Content from '$lib/content/legal/privacy-policy.svx';
	import Seo from '$lib/components/seo.svelte';
</script>

<Seo
	title="Privacy Policy"
	description="Learn how we handle, store, and protect your personal information."
/>

<div class="flex justify-center pt-12">
	<article class="prose w-full max-w-2xl pb-10">
		<Content />
	</article>
</div>

// src/app/(unauthenticated)/(legal)/privacy-policy/page.tsx
import React from 'react';

import { Metadata } from 'next';
import { notFound } from 'next/navigation';

import { CustomMDX } from '@/components/mdx';
import { getLegal } from '@/lib/posts';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description:
    'Learn how we handle, store, and protect your personal information.',
};

export default function PrivacyPolicyPage() {
  const post = getLegal().find((post) => post.slug === 'privacy-policy');

  if (!post) {
    notFound();
  }

  return (
    <div className="pt-12 flex justify-center">
      <article className="prose max-w-2xl pb-10 w-full">
        <CustomMDX source={post.content} />
      </article>
    </div>
  );
}
