// src/routes/(app)/(protected)/dashboard/+page.svelte
<script lang="ts">
	import Seo from '$lib/components/seo.svelte';
	import MaxWidthWrapper from '$lib/components/max-width-wrapper.svelte';
	import FilterAndSortBar from '$lib/components/portfolio/filter-and-sort-bar.svelte';
	import MainContent from '$lib/components/portfolio/main-content.svelte';

	let selectedSort = $state('recentlyAdded');
	let selectedFilter = $state('All');
	let searchValue = $state('');
</script>

<Seo title="Dashboard" />

<MaxWidthWrapper class="pt-4 md:pt-0">
	<span class="block text-3xl font-bold md:hidden md:text-4xl">Dashboard</span>
	<div class="relative pt-2 pb-6">
		<FilterAndSortBar bind:searchValue bind:selectedSort bind:selectedFilter />
		<MainContent {selectedSort} {selectedFilter} {searchValue} />
	</div>
</MaxWidthWrapper>

// src/app/(authenticated)/(main)/dashboard/page.tsx
'use client';

import React, { useState } from 'react';

import FilterAndSortBar from '@/components/filter-and-sort-bar';
import MainContent from '@/components/main-content';
import MaxWidthWrapper from '@/components/max-width-wrapper';

export default function DashboardPage() {
  const [selectedSort, setSelectedSort] = useState<string>('recentlyAdded');
  const [selectedFilter, setSelectedFilter] = useState<string>('All');
  const [searchValue, setSearchValue] = useState('');

  return (
    <MaxWidthWrapper className='pt-4 md:pt-0'>
      <span className="text-3xl md:text-4xl font-bold block md:hidden">Dashboard</span>
      <div className="pb-6 pt-2 relative">
        <FilterAndSortBar
          searchValue={searchValue}
          selectedSort={selectedSort}
          selectedFilter={selectedFilter}
          setSearchValue={setSearchValue}
          setSelectedSort={setSelectedSort}
          setSelectedFilter={setSelectedFilter}
        />
        <MainContent
          selectedSort={selectedSort}
          selectedFilter={selectedFilter}
          searchValue={searchValue}
        />
      </div>
    </MaxWidthWrapper>
  );
}
