// src/lib/components/portfolio/filter-and-sort-bar.svelte
<script lang="ts">
	import { api } from '$convex/_generated/api';
	import ArrowDownAZIcon from '@lucide/svelte/icons/arrow-down-a-z';
	import HeartIcon from '@lucide/svelte/icons/heart';
	import SparklesIcon from '@lucide/svelte/icons/sparkles';
	import { useQuery } from 'convex-svelte';

	import * as Select from '$lib/components/ui/select/index.js';
	import FilterButton from './filter-button.svelte';
	import SearchBox from './search-box.svelte';

	let {
		searchValue = $bindable(''),
		selectedSort = $bindable('recentlyAdded'),
		selectedFilter = $bindable('All')
	}: {
		searchValue?: string;
		selectedSort?: string;
		selectedFilter?: string;
	} = $props();

	const getUniqueTitles = useQuery(api.portfolios.getUniqueTitles, {});

	const uniqueTags = $derived(['All', ...(getUniqueTitles.data ?? [])]);

	const sortLabels: Record<string, string> = {
		recentlyAdded: 'Recently Added',
		mostPopular: 'Most Popular',
		alphabetical: 'Alphabetical'
	};
</script>

{#if getUniqueTitles.data && getUniqueTitles.data.length > 0}
	<div class="flex flex-col items-start gap-4 pb-4 md:flex-row md:items-center md:justify-between">
		<!-- Filter -->
		<div
			class="relative flex w-full justify-start overflow-x-auto pr-8"
			style="mask-image: linear-gradient(to left, transparent 0%, black 20%);"
		>
			{#each uniqueTags as tag (tag)}
				<FilterButton
					label={tag}
					isSelected={selectedFilter === tag}
					onclick={() => (selectedFilter = tag)}
				/>
			{/each}
		</div>
		<!-- Select -->
		<div class="flex w-full items-center justify-end gap-2 md:w-fit">
			<SearchBox bind:searchValue />
			<Select.Root type="single" bind:value={selectedSort}>
				<Select.Trigger class="md:w-[190px]">
					{sortLabels[selectedSort] ?? ''}
				</Select.Trigger>
				<Select.Content class="text-xs">
					<Select.Group>
						<Select.GroupHeading>Sort by</Select.GroupHeading>
						<Select.Item value="recentlyAdded">
							<div class="flex items-center gap-2">
								<SparklesIcon size={16} />
								<span>Recently Added</span>
							</div>
						</Select.Item>
						<Select.Item value="mostPopular">
							<div class="flex items-center gap-2">
								<HeartIcon size={16} />
								<span>Most Popular</span>
							</div>
						</Select.Item>
						<Select.Item value="alphabetical">
							<div class="flex items-center gap-2">
								<ArrowDownAZIcon size={16} />
								<span>Alphabetical</span>
							</div>
						</Select.Item>
					</Select.Group>
				</Select.Content>
			</Select.Root>
		</div>
	</div>
{/if}

// src/components/filter-and-sort-bar.tsx
'use client';

import React from 'react';

import SearchBox from '@/components/search-box';
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { api } from '@/convex/_generated/api';
import { useQuery } from 'convex/react';
import { ArrowDownAZ, Heart,  Sparkles } from 'lucide-react';

import FilterButton from './filter-button';

export default function FilterAndSortBar({
  searchValue,
  selectedSort,
  selectedFilter,
  setSearchValue,
  setSelectedSort,
  setSelectedFilter,
}: {
  searchValue: string;
  selectedSort: string;
  selectedFilter: string;
  setSearchValue: React.Dispatch<React.SetStateAction<string>>;
  setSelectedSort: React.Dispatch<React.SetStateAction<string>>;
  setSelectedFilter: React.Dispatch<React.SetStateAction<string>>;
}) {
  const getUniqueTitles = useQuery(api.portfolios.getUniqueTitles);

  if (!getUniqueTitles || getUniqueTitles.length === 0) return null;

  const uniqueTags = ['All', ...getUniqueTitles];

  return (
    <div className="flex flex-col gap-4 items-start md:flex-row md:justify-between md:items-center pb-4">
      {/* Filter */}
      <div
        className="relative overflow-x-auto w-full justify-start flex pr-8"
        style={{
          maskImage: 'linear-gradient(to left, transparent 0%, black 20%)',
        }}
      >
        {uniqueTags.map((tag) => {
          return (
            <FilterButton
              key={tag}
              label={tag}
              isSelected={selectedFilter === tag}
              onClick={() => {
                setSelectedFilter(tag);
              }}
            />
          );
        })}
      </div>
      {/* Select  */}
      <div className="flex w-full md:w-fit justify-end items-center gap-2">
        <SearchBox searchValue={searchValue} setSearchValue={setSearchValue} />
        <Select
          defaultValue="recentlyAdded"
          value={selectedSort}
          onValueChange={setSelectedSort}
        >
          <SelectTrigger className="md:w-[190px]">
            <SelectValue />
          </SelectTrigger>
          <SelectContent className="text-xs">
            <SelectGroup>
              <SelectLabel>Sort by</SelectLabel>
              <SelectItem value="recentlyAdded">
                <div className="flex items-center gap-2">
                  <Sparkles size={16} />
                  <span>Recently Added</span>
                </div>
              </SelectItem>
              <SelectItem value="mostPopular">
                <div className="flex items-center gap-2">
                  <Heart size={16} />
                  <span>Most Popular</span>
                </div>
              </SelectItem>
              <SelectItem value="alphabetical">
                <div className="flex items-center gap-2">
                  <ArrowDownAZ size={16} />
                  <span>Alphabetical</span>
                </div>
              </SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>
      </div>
    </div>
  );
}
