// src/lib/components/max-width-wrapper.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import { cn } from '$lib/utils.js';

	let { class: className, children }: { class?: string; children: Snippet } = $props();
</script>

<div class={cn('mx-auto flex w-full flex-col px-4 pt-4 pb-8 sm:px-8 lg:px-24', className)}>
	{@render children()}
</div>

// src/components/max-width-wrapper.tsx
import { ReactNode } from 'react';

import { cn } from '@/lib/utils';

export default function MaxWidthWrapper({
  className,
  children,
}: {
  className?: string;
  children: ReactNode;
}) {
  return (
    <div
      className={cn(
        'flex flex-col pt-4 pb-8 sm:px-8 lg:px-24 mx-auto px-4 w-full',
        className,
      )}
    >
      {children}
    </div>
  );
}
