// apps/web/src/app/banner.tsx
import React from 'react';

import Link from 'next/link';

import { ChevronRight } from 'lucide-react';

export default function Banner() {
  return (
    <Link
      target="_blank"
      href="https://projectplannerai.com/"
      className="flex flex-row items-center justify-center w-full h-12 tracking-tight text-white font-medium bg-emerald-600  text-center group text-balance text-sm sm:text-base"
    >
      🚀 Introducing ProjectPlannerAI - Simplify your project management and
      finally finish your projects{' '}
      <ChevronRight
        size={18}
        className="hidden md:block ml-1 group-hover:translate-x-1 transition-all duration-300"
      />
    </Link>
  );
}

// src/lib/components/layout/banner.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button/index.js';
</script>

<div
	class="group flex w-full flex-col items-center justify-center gap-2 bg-emerald-600 px-4 py-3 text-center text-base font-medium tracking-tight text-white transition-all duration-200 sm:flex-row md:text-lg"
>
	<span class="text-base font-medium text-balance">
		✨ Simple Project Management for side projects and indie hackers ✨
	</span>
	<Button
		size="sm"
		href="https://projectplannerai.com/"
		target="_blank"
		class="h-8 w-full bg-white text-black hover:bg-neutral-200 sm:w-fit"
	>
		Try Now
	</Button>
</div>
